# yaml-language-server: $schema=https://json.schemastore.org/dependabot-2.0.json

version: 2

updates:
  - package-ecosystem: "github-actions"
    target-branch: "main"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
    target-branch: "main"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - github.com/bokwoon95/wgo
      - github.com/evilmartians/lefthook
      - github.com/goreleaser/goreleaser/v2
      - honnef.co/go/tools/cmd/staticcheck

  - package-ecosystem: "npm"
    target-branch: "main"
    directory: "/"
    schedule:
      interval: "weekly"
